services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false  
    autoDeploy: true

  - type: web
    name: chatbot-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    autoDeploy: true
